name: code-quality
on:
  push:
    branches-ignore:
      - hotfix/*
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.2.x
          cache: npm

      - name: Install dependencies
        run: npm i

      - name: Run lint
        run: npm run lint

      - name: Run test
        run: npm run test

  push-docker-image:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docker image
        env:
          CONTAINER_NAME: ${{github.repository}}:${{github.sha}}
        run: docker build -t $CONTAINER_NAME .
