name: push-docker-image
on:
  repository_dispatch:
    types: [code-quality]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Greeting
        run: echo "Yeah!"


  